server:
  port: 8083

spring:
  application:
    name: USER-SERVICE

eureka:
  client:
    register-with-eureka:
      fetch-registry: true
      service-url:
        defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost